version: '3.8'

services:
  broker:
    image: kaftarmq/broker:local
    ports:
      - "8080:20000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - net

  router:
    image: kaftarmq/router:local
    ports:
      - "8081:30000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - net

  nginx:
    image: my-nginx-image:latest
    ports:
      - "80:80"
    tty: true
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - broker
      - router
    networks:
      - net

networks:
  net: