global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'broker'
    dns_sd_configs:
      - names:
          - 'tasks.broker'
        type: 'A'
        port: 80

  - job_name: 'router'
    dns_sd_configs:
      - names:
          - 'tasks.router'
        type: 'A'
        port: 80

  - job_name: 'syncer'
    dns_sd_configs:
      - names:
          - 'tasks.syncer'
        type: 'A'
        port: 80

  - job_name: 'nginx'
    dns_sd_configs:
      - names:
          - 'tasks.nginx'
        type: 'A'
        port: 80

  - job_name: 'node'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: 'A'
        port: 9100

rule_files:
  - "rules.yml"
