global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'broker'
    static_configs:
      - targets: ['localhost:80']
    metrics_path: '/broker/metrics'

  - job_name: 'router'
    static_configs:
      - targets: ['localhost:80']
    metrics_path: '/router/metrics'

  - job_name: 'syncer'
    static_configs:
      - targets: ['localhost:80']
    metrics_path: '/syncer/metrics'
