{
 "title": "monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "job:instances:count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "job:instances:count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "job:memory:used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "job:memory:used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "router:push_requests_per_second_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "router:push_requests_per_second_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "router:push_requests_per_second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "router:push_requests_per_second",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}