name: Docker Swarm CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Copy configuration files to the server
        continue-on-error: true  # This allows the workflow to continue if this step fails
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SWARM_MANAGER_IP }}
          username: ${{ secrets.SWARM_MANAGER_USERNAME }}
          password: ${{ secrets.SWARM_MANAGER_PASSWORD }}
          source: "grafana/,prometheus.yml,rules.yml"
          target: "/home/kaftarmq/configs"

      - name: Deploy to Docker Swarm
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWARM_MANAGER_IP }}
          username: ${{ secrets.SWARM_MANAGER_USERNAME }}
          password: ${{ secrets.SWARM_MANAGER_PASSWORD }}
          script: |
            cd /home/kaftarmq
            docker stack deploy --compose-file docker-compose.yml kaftarmq --with-registry-auth
