name: Docker Swarm CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

#      - name: Deploy to Docker Swarm
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SWARM_MANAGER_IP }}
#          username: ${{ secrets.SWARM_MANAGER_USERNAME }}
#          key: ${{ secrets.SWARM_MANAGER_SSH_KEY }}
#          script: |
#            export DOCKER_HOST=tcp://${{ secrets.SWARM_MANAGER_IP }}:2375
#            docker stack deploy --compose-file docker-compose.yml myapp
